#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.
url                                       : http://localhost:4000/              # The URL of your github pages site

# App Info
ios_app_id                                : 1136800740                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : http://localhost:4000/assets/gametrack-icon-main.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Making managing your games collection easy and enjoyable.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Joe Kimberlin-Wyer                                
your_link                                 :                      
your_city                                 : London                                
email_address                             : joe.kw@me.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : getgametrack
github_username                           : joekw
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Gaming Collections
    description                           : Keep track of your video game backlog, archive and wish list with beautiful poster and banner images.
    fontawesome_icon_name                 : gamepad
    
  - title                                 : Share Your Gaming Life
    description                           : Post updates to your feed when you start, finish, or wish for a game and search for your friends lists.
    fontawesome_icon_name                 : share

  - title                                 : Add Any Game
    description                           : Using the IGDB.com database, search for any game on any platform to add to your lists.
    fontawesome_icon_name                 : plus

  - title                                 : Rate Games & Track Progress
    description                           : Keep track of your progress through your backlog and rate your games when finished. Hold down on a game in your list to quickly change these.
    fontawesome_icon_name                 : star

  - title                                 : Link your gaming accounts
    description                           : Link your PSN, Xbox & Steam accounts to import your games along with trophies and achievements.
    fontawesome_icon_name                 : trophy
  
  - title                                 : Customisation
    description                           : Change up your experience with multiple themes, tint colours and custom icons (based on PS4, Xbox & Switch controllers).
    fontawesome_icon_name                 : adjust

  - title                                 : Notifications
    description                           : Get notifications when your most anticipated games are released.
    fontawesome_icon_name                 : bell

  - title                                 : Charts & Statistics
    description                           : View automatic charts of your ratings, favourite platforms, genres and how many games you finish per month.
    fontawesome_icon_name                 : chart-line

  - title                                 : Ranked Lists
    description                           : Create custom ranked lists for your favourite games and series.
    fontawesome_icon_name                 : medal



# Theme Settings
topbar_color                              : "#1B1F28"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#1B1F28"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#00D5E5"
feature_text_color                        : "#ffffff"

feature_icons_foreground_color            : "#00D5E5"
feature_icons_background_color            : "#131920"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#ffffff"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
