#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : #1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : pt-br                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://twitter.com/bluesprogrammer                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : CrossfitPR App                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Organize your personal records in crossfit workouts.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.


# Information About Yourself
your_name                                 : Douglas Taquary                                
your_link                                 : https://twitter.com/bluesprogrammer                     
your_city                                 : SÃ£o Paulo                                
email_address                             : douglastaquary@gmail.com
facebook_username                         : #                                          
instagram_username                        : senhordeengenho
twitter_username                          : twiiter
github_username                           : douglastaquary
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Keep your PR hassle free
    description                           : Organizing your personal records makes the evolution of your exercises more practical
    fontawesome_icon_name                 : dumbbell

  - title                                 : Insights
    description                           : The powerful insights elevator allows you to understand your biggest records and the evolution of others.
    fontawesome_icon_name                 : chart-bar

  - title                                 : Recommendations
    description                           : An intelligent recommendations system gives you hints on best personal records.
    fontawesome_icon_name                 : comment

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color                              : "#000"
topbar_transparency                       : 0.0
topbar_title_color                        : "#000"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000"
cover_overlay_transparency                : 0.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000"

link_color                                : "#34C759"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#34C759"
feature_icons_background_color            : "#222"

social_icons_foreground_color             : "#34C759"
social_icons_background_color             : "#222"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
