#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Subnets made simple. 

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nick Smart                            
your_link                                 :                  
your_city                                 :                               
email_address                             : codelab703@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : nicholassmart
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Subnet Calculator
    description                           : Calculate subnet mask, wildcard, network ID, host range, and broadcast addresses with an IPv4 address. Dynamically view variations based on CIDR network and view binary code. 
    fontawesome_icon_name                 : magic
    
  - title                                 : Fixed Length Subnet Mask (FLSM)
    description                           : Dynamically calculate up to 1024 FLSM subnets to suite your requirements and view detailed configuration information for each one. 
    fontawesome_icon_name                 : mobile

  - title                                 : Variable Length Subnet Mask (VLSM)
    description                           : Instantly calculate VLSM subnets based on your custom host requirements and view view detailed configuration information for each one. 
    fontawesome_icon_name                 : mobile

  - title                                 : Powerful Views
    description                           : Dig deeper into your subnets by viewing complete binary addresses with just a rotation of your device. 
    fontawesome_icon_name                 : adjust

  - title                                 : Save Support
    description                           : Seamlessy save your networks for later use using CoreData.  
    fontawesome_icon_name                 : sync
  
  - title                                 : Native
    description                           : Written in Swift code and designed for iOS, subnet with the same intuitive user expereince you expect from your device.  
    fontawesome_icon_name                 : star



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
