#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1604573775                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : de                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/de/app/golf-logbuch/id1538956880   # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Golf Logbook                              # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : With this app you can record and evaluate your training times. To do this, you only have to record the training duration per category (course, driver, wood, iron, ...) and you can then get an overview of your training in the form of a line diagram per month or a pivot table per year and month. It is also possible to define training tasks with a time period and scope. As part of the time recording for each category, you can then also specify whether and to what extent you have worked on a task. The task overview also gives you the opportunity to see to what extent your tasks have already been completed. All data is saved locally in the app and can be exported as well as imported in JSON format. This makes it possible, for example, to convert the recorded and exported training data from JSON to CSV and process it in Excel with little effort.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Christian Rehn
your_link                                 :
your_city                                 :
email_address                             :
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           : christianrehn
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Need Help
    description                           : You need help or have any questions? Please contact me at golf.logbook@gmail.com
    fontawesome_icon_name                 : mobile

  - title                                 : Additional Requirements
    description                           : You have additional ideas or new requirements to track your training data? Send a request to golf.logbook@gmail.com
    fontawesome_icon_name                 : adjust

  - title                                 : You have a QCQuad/GC3/GC2
    description                           : Check out my QCQuad Combine Test Application https://christianrehn.github.io/GCQuadCombineTest
    fontawesome_icon_name                 : magic # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
