#page title
page_title                                : flosell.app                                      # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apple.com                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://google.com                                          # Enter Google Play Store URL.
#presskit_download_link                    : https://airtable.com/shrg1VfLskzn81LAy                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Earn Money Selling Store's Owner Products to People you care about. <!-- **Find out what you could earn:**

enable_smart_app_banner                   : true                                     # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Suleman
your_link                                 : https://
your_city                                 : Dubai
email_address                             : suleman@useorder.com
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :




# Theme Settings
topbar_color                              : "#3d95ce"
topbar_transparency                       : 1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerBack.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#3d95ce"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#3d95ce"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1a8bfb"
feature_icons_background_color            : "#1a8bfb"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
